/** Names accepted by `<Icon name=… />` (inline Lucide glyphs, MIT). */
export type IconName =
  | 'smartphone'
  | 'shield'
  | 'key'
  | 'zap'
  | 'fingerprint'
  | 'globe'
  | 'terminal'
  | 'code'
  | 'lock'
  | 'server'
  | 'git-branch'
  | 'check'
  | 'arrow-right'
  | 'bluetooth'
  | 'qr'
  | 'link'
  | 'radio'
  | 'copy'
  | 'book'
  | 'layers'
  | 'building'
  | 'mail'
  | 'x';
